# This should be kept in line with concordium-consensus/stack.yaml and
# concordium-base/stack.yaml

resolver: lts-19.6

packages:
- ./concordium-base
- ./concordium-consensus

extra-deps:
- ./concordium-consensus/haskell-lmdb

extra-lib-dirs:
- ./concordium-base/lib
- ./concordium-consensus/smart-contracts/lib
- /opt/homebrew/lib

extra-include-dirs:
- /opt/homebrew/include/
- /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/ffi/
