#!/usr/bin/env bash

set -x

# Haskell binding needs proper library path to function
export LD_LIBRARY_PATH=/usr/local/lib

ARGS=""

if [ -n "$CONCORDIUM_NODE_CONFIG_DIR" ];
then
    mkdir -p $CONCORDIUM_NODE_CONFIG_DIR
fi

if [ -n "$CONCORDIUM_NODE_DATA_DIR" ];
then
    mkdir -p $CONCORDIUM_NODE_DATA_DIR
    cd $CONCORDIUM_NODE_DATA_DIR
fi

if [ -n "$ARTIFICIAL_DELAY" ];
then
    sleep $ARTIFICIAL_DELAY
fi

if [ -n "$PROFILING_ARGS" ];
then
    ARGS="$ARGS $PROFILING_ARGS"
fi

if [ -n "$TRUSTED_NODES_FILE" -a -f "$TRUSTED_NODES_FILE" ];
then
    readarray -t host_ports < "$TRUSTED_NODES_FILE"
    for host_port in "${host_ports[@]}"; do
        ARGS="$ARGS --connect-to $host_port"
    done
fi

if [ "$MODE" == "basic" ]; then
    /usr/bin/concordium-node $ARGS
elif [ "$MODE" == "bootstrapper" ]; then
    /usr/bin/p2p_bootstrapper-cli $ARGS
elif [ "$MODE" == "collector" ]; then
    /usr/bin/node-collector $ARGS
else
    echo "No matching MODE was found. Please check!"
fi
