[package]
name = "custom-actions"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3", features = ["winnt", "winerror", "winsvc"] }

[lib]
crate-type = ["cdylib"]