name:                concordium-consensus
version:             0.1.0.0
github:              "Concordium/concordium-node"
license:             AGPL-3.0
license-file:        "../LICENSE"
author:              "Concordium"
maintainer:          "developers@concordium.com"
copyright:           "Concordium"

extra-source-files:
- README.md
- ChangeLog.md

custom-setup:
  dependencies:
    - base  >= 4.7
    - Cabal >= 2.2
    - directory >= 1.3

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Concordium#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- random >= 1.1
- cereal >= 0.5.7
- data-fix >= 0.3
- exceptions >= 0.10
- unordered-containers >= 0.2
- hashable >= 1.0.1.1
- containers >0.5.9.1
- time >=1.8
- transformers >=0.5
- microlens-platform >=0.3
- microlens >=0.3
- mmap >=0.5
- mtl >=2.2
- pqueue >= 1.4.1
- psqueues >= 0.2.7
- vector >= 0.12
- concordium-base
- base16-bytestring
- aeson >= 1.4.2
- attoparsec >= 0.14.4
- text >= 1.2
- filepath >= 1.4
- directory >= 1.3
- monad-logger >= 0.3.30
- recursion-schemes >= 5.1
- file-embed >= 0.0.11
- lmdb
- primitive
- proto-lens >= 0.7
- singletons-base

default-extensions:
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- RecordWildCards
- TupleSections
- TypeOperators

flags:
  dynamic:
    manual: True
    default: True

library:
  source-dirs: src
  ghc-options:
      - -Wall
      - -Wcompat
      - -Werror=missing-fields
      - -Werror=missing-methods
      - -Wredundant-constraints
      - -O2
      - -fno-ignore-asserts

  extra-libraries: concordium_smart_contract_engine

  when:
    - condition: "!(os(windows)) && !(flag(dynamic))"
      # When we are building a statically linked node, we include the ffi interface in the
      # library, and will not build the foreign-library.
      ghc-options: -fPIC -static -fno-link-rts
      source-dirs: src-lib

# We use a foreign-library stanza to build the consensus library for dynamic linking.
# This is more robust than the previous approach where the library as a whole was built as a
# DLL or shared object with specific ghc-options. At the time of writing, stack does not support
# the foreign-library stanza, so we include it in a verbatim block as it will be output in the
# cabal file.

# On Windows, the previous build setup produced HSdll.dll in the `concordium-consensus` directory.
# The new approach builds a `concordium-consensus.dll` under `.stack-work\install\...\lib`.
# Since the mod-def-file is specified in its own field (rather than under ghc-options), it does not
# interfere with building the haddock documentation on Windows.

verbatim: |
  foreign-library concordium-consensus
    type: native-shared
    ghc-options: -Wall -Wcompat -Werror=missing-fields -Werror=missing-methods -Wredundant-constraints -O2 -fno-ignore-asserts -threaded
    if os(Windows)
      options: standalone
      mod-def-file: lib.def
      -- -fPIC casues issues on Windows: https://gitlab.haskell.org/ghc/ghc/-/issues/24016
      -- However, it should not do anything on Windows anyway, so we disable it.
      -- (Otherwise, cabal enables it.)
      ghc-options: -fno-PIC
    else
      if flag(dynamic)
        ghc-options: -fPIC
      else
        -- The foreign library should not be built when doing a static build of the node.
        buildable: False
    
    other-modules:
      Concordium.External
      Concordium.External.DryRun
      Concordium.External.Helpers
      Concordium.External.GRPC2
    hs-source-dirs: src-lib
    build-depends: 
        aeson
      , bytestring
      , cereal
      , containers
      , directory
      , filepath
      , microlens-platform
      , proto-lens
      , transformers
      , vector
      , base
      , text
      , concordium-base
      , concordium-consensus
    default-language: Haskell2010
    default-extensions:
      FlexibleContexts
      FlexibleInstances
      FunctionalDependencies
      GeneralizedNewtypeDeriving
      KindSignatures
      LambdaCase
      MultiParamTypeClasses
      RecordWildCards
      TupleSections
      TypeOperators

executables:
  Concordium-exe:
    main:                Main.hs
    source-dirs:         test-runners/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
      - concordium-consensus

  deterministic-runner:
    main:                Main.hs
    source-dirs:         test-runners/deterministic
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
      - concordium-consensus

  catchup-runner:
    main:                Main.hs
    source-dirs:         test-runners/catchup
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus

  execute-chain:
    main:                Main.hs
    source-dirs:         test-runners/execute-chain
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - clock

  database-exporter:
    main:         Main.hs
    source-dirs:  tools/database-exporter
    ghc-options:
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -threaded

    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - optparse-applicative >= 0.15
    - filepath >= 1.4

tests:
  consensus:
    main:                Spec.hs
    source-dirs:         tests/consensus
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - hspec >= 2.5
    - QuickCheck >= 2.10
    - hspec-expectations >= 0.8
    - HUnit >= 1.6
    - vector >= 0.12
    - math-functions >= 0.2
    - temporary >= 1.3

  globalstate:
    main:                Spec.hs
    source-dirs:         tests/globalstate
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - hspec >= 2.6
    - QuickCheck >= 2.12
    - hspec-expectations >= 0.8
    - containers
    - time >= 1.8
    - random >= 1.1
    - HUnit >= 1.6
    - temporary >= 1.3
    - monad-loops


  scheduler:
    main:                Spec.hs
    source-dirs:         tests/scheduler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - hspec >= 2.6
    - HUnit >= 1.6
    - QuickCheck >= 2.12
    - hspec-expectations >= 0.8
    - containers
    - microlens-platform >= 0.3
    - aeson >= 1.4.2
    - filepath >= 1.4.2
    - template-haskell
    - temporary >= 1.3

benchmarks:
  trie:
    main:                TrieBench.hs
    source-dirs:         benchmarks/trie
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - containers
    - temporary >= 1.3
    - criterion
    - deepseq

  credential-lookup:
    main:                CredentialLookup.hs
    source-dirs:         benchmarks/credential-lookup
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - containers
    - temporary >= 1.3
    - criterion
    - deepseq

  leader-election:
    main:                LeaderElectionBench.hs
    source-dirs:         benchmarks/leader-election
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - containers
    - temporary >= 1.3
    - criterion
    - deepseq

  transactions:
    main:                TransactionsBench.hs
    source-dirs:         benchmarks/transactions
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1
    - -Wall
    - -Wcompat
    - -fno-ignore-asserts
    - -Wno-deprecations
    when:
      - condition: os(windows)
        then:
          ghc-options: -static
        else:
          when:
            - condition: flag(dynamic)
              then:
                ghc-options: -dynamic
              else:
                ghc-options: -static
    dependencies:
    - concordium-consensus
    - containers
    - temporary >= 1.3
    - criterion
    - deepseq
