#!/bin/bash

set -euo pipefail

readonly nodeDir="/Library/Concordium Node/__VERSION__"
readonly localBinDir="/usr/local/bin"

readonly node="$nodeDir/concordium-node"
readonly nodeSymlink="$localBinDir/concordium-node-__VERSION__"
readonly collector="$nodeDir/concordium-node-collector"
readonly collectorSymlink="$localBinDir/concordium-node-collector-__VERSION__"

# Remove existing symlinks if present
if [ -f "$nodeSymlink" ]; then
    rm -f "$nodeSymlink"
fi
if [ -f "$collectorSymlink" ]; then
    rm -f "$collectorSymlink"
fi

# Add new symlinks
ln -s "$node" "$nodeSymlink"
ln -s "$collector" "$collectorSymlink"
