#!/bin/bash

echo "Running postinstall script"

readonly nodeDir="/Library/Concordium Node/__VERSION__"
readonly installConfigFile="/tmp/concordium.node.install.config"
readonly serviceFileCollectorMainnet="/Library/LaunchDaemons/software.concordium.node-collector.plist"

# Ensure the local bin folder exists
echo "Ensuring '/usr/local/bin' exists"
if [ ! -d "/usr/local/bin" ]; then
    mkdir "/usr/local/bin"
fi

# Create/replace symlinks that are in PATH
echo "Creating symlinks to node and collector"
ln -f -s "$nodeDir/concordium-node" "/usr/local/bin/concordium-node-__VERSION__"
ln -f -s "$nodeDir/node-collector" "/usr/local/bin/concordium-node-collector-__VERSION__"

# Use data from install configuration
echo 'Configuring services'
source "$installConfigFile"
sed -i '' -e 's/__NODE_NAME__/'"$NODE_NAME_MAINNET"'/g' "$serviceFileCollectorMainnet"

echo "Postinstall finished"
exit 0
