#!/bin/bash

set -euo pipefail

readonly nodeInLibrary="/Library/concordium-node/__VERSION__/concordium-node"
readonly nodeInBin="/usr/local/bin/concordium-node-__VERSION__"

# Remove existing symlink if present
if [ -f "$nodeInBin" ]; then
    rm -f "$nodeInBin"
fi

# Add new symlink
ln -s "$nodeInLibrary" "$nodeInBin"
