#!/bin/bash

set -e

function removeFileIfExists() {
    local theFile=${1:?"removeIfExists expects 1 argument: file"}
    if [ -f "$theFile" ]
    then
        echo "     $theFile"
        sudo rm "$theFile"
    fi
}

function removeServiceIfExists() {
    local service=${1:?"removeServiceIfExists expects 1 argument: service-name"}

    if sudo launchctl list "$service" &> /dev/null
    then
        echo "     $service"
        sudo launchctl remove "$service"
    fi
}

function removeSymlinks(){
    removeFileIfExists "/usr/local/bin/concordium-node"
    removeFileIfExists "/usr/local/bin/concordium-node-collector"
}

function removeLaunchDaemons(){
    echo "Removing launch daemons"

    echo "-- Removing the following services from launchctl:"
    removeServiceIfExists "software.concordium.mainnet.node"
    removeServiceIfExists "software.concordium.mainnet.node-collector"
    removeServiceIfExists "software.concordium.testnet.node"
    removeServiceIfExists "software.concordium.testnet.node-collector"
}

# Removes the binaries and report-to-dashboard files if they exist.
# Does not touch launch daemon files and files created by the user.
function removeFilesInNodeDir(){
    local nodeDir="/Library/Concordium Node"
    if [ -d "$nodeDir" ]
    then
        echo "-- Deleting the following files from '$nodeDir':"
        removeFileIfExists "$nodeDir/concordium-node"
        removeFileIfExists "$nodeDir/node-collector"
        removeFileIfExists "$nodeDir/REPORT_TO_NETWORK_DASHBOARD_MAINNET"
        removeFileIfExists "$nodeDir/REPORT_TO_NETWORK_DASHBOARD_TESTNET"
    fi
}

function main(){
    echo "Running preinstall script"

    removeLaunchDaemons

    removeSymlinks

    removeFilesInNodeDir

    echo "Preinstall finished"
}

main
