version: '3'
services:
    bootstrapper:
        image: concordium/dev-client:develop
        depends_on:
            - baker_id_gen
            - collector_backend
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - MODE=local_bootstrapper
            - EXTRA_ARGS=${EXTRA_ARGS}
        entrypoint:
            - /start.sh
    postgresql:
        image: postgres:latest
        environment:
          POSTGRES_PASSWORD: concordium
          POSTGRES_USER: concordium
          POSTGRES_DB: concordium
        ports:
            - "5432:5432"
    collector_backend:
        image: concordium/dev-client:develop
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - MODE=local_collector_backend
            - COLLECTOR_BACKEND_PORT=10000
            - COLLECTOR_BACKEND_HOST=0.0.0.0
            - EXTRA_ARGS=${EXTRA_ARGS}
        entrypoint:
            - /start.sh
        ports:
            - "12000:10000"
    baker_id_gen:
        image: concordium/dev-client:develop
        entrypoint:
            - /baker_id_generator
    baker:
        image: concordium/dev-client:develop
        depends_on:
            - bootstrapper
            - postgresql
        entrypoint:
            - /start.sh
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - DESIRED_PEERS=${DESIRED_PEERS}
            - BOOTSTRAP_FIRST_NODE=bootstrapper:8888
            - EXTERNAL_PORT=8888
            - NUM_BAKERS=${NUM_BAKERS}
            - MODE=local_basic
            - DATA_DIR=/var/lib/concordium/data
            - RPC_SERVER_ADDR=0.0.0.0
            - EXTRA_ARGS=${EXTRA_ARGS}
            - TRANSACTION_OUTCOME_LOGGING=1
            - TRANSACTION_OUTCOME_LOGGING_HOST=postgresql
            - TRANSACTION_OUTCOME_LOGGING_PORT=5432
            - TRANSACTION_OUTCOME_LOGGING_NAME=concordium
            - TRANSACTION_OUTCOME_LOGGING_USERNAME=concordium
            - TRANSACTION_OUTCOME_LOGGING_PASSWORD=concordium
            - DB_SLEEP=${DB_SLEEP:-15}
        ports:
            - "11100-11500:10000"
    collector:
        image: concordium/dev-client:develop
        depends_on:
            - baker
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - MODE=local_collector
            - NUM_BAKERS=${NUM_BAKERS}
            - COLLECTOR_SLEEP=${COLLECTOR_SLEEP:-15}
            - COLLECTOR_URL=http://collector_backend:10000/nodes/post
            - EXTRA_ARGS=${EXTRA_ARGS}
        entrypoint:
            - /start.sh
    wallet_proxy:
        image: concordium/dev-client:develop
        depends_on:
            - baker
            - postgresql
        environment:
            - MODE=local_wallet_proxy
            - WALLET_PROXY_GRPC_IP=p2p-client_baker_1
            - WALLET_PROXY_GRPC_PORT=10000
            - WALLET_PROXY_DATABASE="host=postgresql port=5432 user=concordium dbname=concordium password=concordium"
            - DB_SLEEP=${DB_SLEEP:-30}
        entrypoint:
            - /start.sh
        ports:
            - "14000:3000"
