# Workflow triggered by pushes to the main branch and PRs targeting it
# (as long as the commits contain Haskell code changes).

# The workflow consists of the single job 'fourmolu'
# which checks formatting of the Haskell sources using the 'fourmolu' tool.
# The job is skipped if the workflow was triggered by a PR
# marked as a draft.

name: Run fourmolu

on:
  push:
    branches: main
    paths:
    - '.github/workflows/fourmolu.yaml'
    - 'fourmolu.yaml'
    - '**.hs'
  pull_request:
    branches: main
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
    - '.github/workflows/fourmolu.yaml'
    - 'fourmolu.yaml'
    - '**.hs'
  workflow_dispatch: # allow manual trigger

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - name: Download fourmolu
      uses: supplypike/setup-bin@v1
      with:
        uri: 'https://github.com/fourmolu/fourmolu/releases/download/v0.9.0.0/fourmolu-0.9.0.0-linux-x86_64'
        name: 'fourmolu'
        version: '0.9.0.0'

    - name: Checkout project
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # Since fourmolu uses the project cabal file to find default language extensions, this step is
    # needed to generate a cabal file from the package.yaml.
    - name: Setup the project
      run: |
        stack --stack-yaml concordium-consensus/stack.yaml setup

    - name: Run fourmolu
      run: |
        fourmolu --color always --mode check --check-idempotence $(git ls-files '*.hs')
